# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Split keyboard support
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Kyria OLED Display
CONFIG_ZMK_DISPLAY=y

# Per key RGB lighting
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=30
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=50
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

# Battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# USB
CONFIG_ZMK_USB=y

# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB_INIT_PRIORITY=50

# ZMK studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=y